### ISSUE TITLE
Nullreference Exception on short Datasets

### ISSUE THREAD

**Issue by TASchwarz** [curiosity-ai/umap-sharp#4]
Any float[][] shorter than ~10  Elements (Such as people would use to test things) crashes with a NullreferenceExeption 
due to Tree.cs line 27 Hyperplane being initialized to null when a Tree has fewer indicies than leaves.

**Comment by theolivenbaum** [comment]
closed by #5

**Comment by theolivenbaum** [comment]
Fix is available on the latest release: https://www.nuget.org/packages/UMAP/1.0.21965
